wifi_ssid: "IoT_PKRU"
wifi_password: "Pkru123456"
fallback_ap_password: "B72B31715592CBC4D965DF7B"
api_encryption_key: "Bdyh15q4TMCup/bwuUI5SPySp6NiV8vT0evTLNnd00A="
ota_password: "F3430C4AF49106A66B6787573BB9531B"
firebase_latest_url: "https://iot-106-default-rtdb.asia-southeast1.firebasedatabase.app/lab/esp32/latest.json"
firebase_history_url: "https://iot-106-default-rtdb.asia-southeast1.firebasedatabase.app/lab/esp32/history.json"
